ALTER TABLE leads ADD COLUMN IF NOT EXISTS utm_source VARCHAR(200) DEFAULT '';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS utm_medium VARCHAR(200) DEFAULT '';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS utm_campaign VARCHAR(200) DEFAULT '';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS utm_content VARCHAR(200) DEFAULT '';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS utm_term VARCHAR(200) DEFAULT '';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS yclid VARCHAR(200) DEFAULT '';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS city VARCHAR(50) DEFAULT '';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS landing_url TEXT DEFAULT '';